---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: invoices-svc
  name: invoices-svc
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: invoices-svc
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: invoices-svc
    spec:
      containers:
      - image: invoices_svc:prueba_db4
        imagePullPolicy: IfNotPresent
        name: invoices-svc
        ports:
        - containerPort: 8080
        env:
        - name: EXPECTED_DATE_URI
          value: http://expected-date-svc.default.svc.cluster.local
        - name: INVOICE_DB_HOST
          value: invoices-svc-mysql
        - name: INVOICE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: invoices-svc
  name: invoices-svc
  namespace: default
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  fws-invoices_mapping
      prefix: /invoices/
      rewrite: /api/invoices/
      service: invoices-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: invoices-svc
  sessionAffinity: None
  type: ClusterIP
